### ISSUE TITLE
Problems with typescript

### ISSUE THREAD

**Issue by esteban142536** [robertosousa1/replace-special-characters#2]
I have problems with syntaxis in typescript, they told me to do @types, but the @types don't exist

**Comment by robertosousa1** [comment]
Hi @esteban142536 .

Would you like to open a Pull Request for our review? 

If not, we will be working internally.

Thanks for your interaction.

**Comment by esteban142536** [comment]
Thanks, but I prefer to wait until an official update

**Comment by esteban142536** [comment]
The issue appears to be fixed
